<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\CitizenPlatform.Application\CitizenPlatform.Application.csproj" />
    <ProjectReference Include="..\CitizenPlatform.Infrastructure\CitizenPlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\CitizenPlatform.Integrations\CitizenPlatform.Integrations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
